name: TestPlugin
main: com.example.testplugin.TestPlugin
version: 1.0.0
api-version: 1.20
authors:
  - ChatGPT
commands:
  testplugin:
    description: Simple test command to verify the plugin works.
    usage: /testplugin
