name: WatchboxManiacTest
main: TestPlugin
version: 1.0.0
api-version: 1.20
commands:
  maniacdebug:
    description: Debug control for Maniac round
    usage: /maniacdebug <subcommand>
  maniac:
    description: Maniac gameplay controls and items
    usage: /maniac <votebook|killersign|silence|swap|showmarks>
  vote:
    description: Cast a vote during the voting phase
    usage: /vote <player>
  role:
    description: Assign or view roles
    usage: /role set <player> <MANIAC|CIVILIAN> | /role get <player>
  round:
    description: View or edit round timing
    usage: /round info | /round time <seconds>
