name: BlackFlashPlugin
main: TestPlugin
version: 1.1.0
api-version: 1.20
commands:
  dbgrole:
    description: Debug command to set or get player roles.
    usage: /dbgrole set <player> <murderer|innocent> | /dbgrole get [player]
  dbgweapon:
    description: Debug command to give the murderer marking weapon.
    usage: /dbgweapon [player]
  dbghighlight:
    description: Highlight players by role or marked entities.
    usage: /dbghighlight role <murderer|innocent> | /dbghighlight marked
  blackflash:
    description: Debug command for the Black Flash ability.
    usage: /blackflash give [player]
